### ISSUE TITLE
Automatically move uncompleted tasks to the next day

### ISSUE THREAD

**Issue by Bejasc** [tgrosinger/slated-obsidian#13]
**Is your feature request related to a problem? Please describe.**
I flip between using Todoist and Markdown Checklists inside Obsidian for managing my tasks and workload for the day. I use Obsidian heavily daily, including the use of checklists in a "To-do List". 

Frequently, I will miss a task on a particular day, and a reflection period over the notes form the previous day is not part of my schedule. 
Because of this, items are missed very often, which leads to overloading on tasks the next day, which causes a bit of a snowball affect on "how much I can get done"

**Describe the solution you'd like**
A task which is created with a particular handle/format - if left unchecked in the previous note, will automatically be copied over when a new daily note is created. 

e.g
`- [ ] Do this thing >>`

Represented in Preview mode as 
- [ ] Do this Thing
It will continue to show up in all daily notes, until it has been completed. 

**Describe alternatives you've considered**
- Implement a "Previous Day" review/reflection process, and continue to manually copy and paste
- Rely on Todoist for this part of my workflow (I have tried the ToDoist plugin, but found it difficult to fit into my daily notes

**Comment by tgrosinger** [comment]
Hey @Bejasc, Thanks for the suggestion.

There is a plugin called [Rollover Daily Todos](https://github.com/shichongrui/obsidian-rollover-daily-todos) which might work for what you need.

I also have plans for adding a view in Slated which shows overdue tasks, which I think might also fit what you need. That is probably the next thing I am going to work on, but it will take a little bit before its ready.

Let me know if either of those sound like they will work for you.

**Comment by Bejasc** [comment]
Thanks - I'll check out Rollover Daily Todos! 

I've been away from my PC over the holiday break, and this looks relatively new, so I missed it! 

Other than that, I'm looking forward to the overdue tasks functionality - it would be great to further enhance and summarize tasks created in markdown.

**Comment by liamcain** [comment]
Totally off-topic but I don't think the Rollover Daily Todos is working, so I wouldn't recommend it. Also, I actually think that functionality could fit nicely baked into slated 🙊 . Especially since you could still have it working with the blockrefs.

**Comment by Bejasc** [comment]
@liamcain You're right, it looks like they're having some issues with the File API obsidian-rollover-daily-todos/#3

I think what would be nice (which as far as I can tell, rollover and slated don't address) would be that the headings remain intact and are copied over too, where they do not exist. 

For example, this is from my Daily Note template 
![image](https://user-images.githubusercontent.com/12091874/103827360-b842d100-50c8-11eb-9c8a-dee8a769d395.png)

The next daily note is created with the same headings.
But if some unfinished tasks remain under those headings, it will copy them over to the _same_ headings.

**Comment by tgrosinger** [comment]
I'm going to move maintaining headings into its own issue, because that would apply for moving and repeating tasks too.

**Comment by tgrosinger** [comment]
I believe I have come up with a good compromise. I have added a command to move all incomplete tasks to "today". Let me know what you think. I'll be releasing it shortly.
