### ISSUE TITLE
Un-defer a task

### ISSUE THREAD

**Issue by liamcain** [tgrosinger/slated-obsidian#19]
**Is your feature request related to a problem? Please describe.**
If I move a task to this friday, then try to move it back, it shows up again on today but still shows up defered.

**Describe the solution you'd like**
I think it should probably just 'undefer' the task.

**Comment by tgrosinger** [comment]
@liamcain do you think it should remove the task entirely from the "friday" file in your example? Or should the Friday file show it as both moved from and moved to Tuesday file?

The Tuesday file should definitely only show the task one time, but no longer have it shown as moved to another day.

**Comment by liamcain** [comment]
I think removed if it goes back to the origin.
