### ISSUE TITLE
Weekly Undone Collection

### ISSUE THREAD

**Issue by Tricksturdoesstuff** [tgrosinger/slated-obsidian#2]
A thought I had is maybe it could collect all TODO items that were not checked off for the previous week into a new weekly note.

**Comment by tgrosinger** [comment]
Great idea. I think this will be a supported workflow in the Perspectives functionality that @ryanjamurphy has mentioned starting to develop.

**Comment by ryanjamurphy** [comment]
Ugh the pressure!

But yes, the search plugin I've got goin' should be able to handle this no problem.

**Comment by tgrosinger** [comment]
No pressure! I'm starting to think that your plugin might actually be closer to the "agenda view" I'm imaging to dig up old uncompleted tasks, and the one I am imaging to compliment it would be aimed at scheduling tasks into the future. But still developing 🙂

**Comment by tgrosinger** [comment]
I believe this will be satisfied by the task list view being created in #25.
