### ISSUE TITLE
cannot load plugin

### ISSUE THREAD

**Issue by julianstoerig** [tgrosinger/slated-obsidian#20]
I could "install" the plugin via obsidian, but when attempting to activate it, I get "Failed to load plugin slated-obsidian.".

## Desktop
 - OS: Windows 10
 - Obsidian Version: v0.10.6
 - Slated Version: 0.0.3

**Comment by tgrosinger** [comment]
Can you please open the console (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>) and let me know what's in there? Switch to the Console tab, and make sure it says "All levels". See the image below:

![image](https://user-images.githubusercontent.com/597386/103687960-f95ea800-4f45-11eb-94c1-c5e02f49f9d1.png)

**Comment by julianstoerig** [comment]
![image](https://user-images.githubusercontent.com/55281225/103689645-e5da2e00-4f93-11eb-8a5b-eb3c4dda0ffe.png)

My "..\\.obsidian\plugins\slated-obsidian" directory actually seems to only contain a json file. I already reinstalled the plugin and even reinstalled obsidian completely though.
![image](https://user-images.githubusercontent.com/55281225/103690010-5d0fc200-4f94-11eb-9bd9-537112005a18.png)

**Comment by tgrosinger** [comment]
That is very strange. I am not sure what could be causing that, because the files are in the release.

Well it should be fixable by downloading `main.js` and `styles.css` from [this release](https://github.com/tgrosinger/slated-obsidian/releases/tag/0.0.3) and putting them in that folder.

Let me know how it goes.

**Comment by julianstoerig** [comment]
Yeah, seems to work just fine, at least there's no more error messages upon loading the plugin. I'm going test it this evening and close the issue if there's no more problems after this.

Have a great day!

**Comment by julianstoerig** [comment]
Works just fine!

**Comment by julianstoerig** [comment]
Works just fine!

**Comment by tgrosinger** [comment]
Awesome, thank you.
