### ISSUE TITLE
0.0.4 failing to load/update

### ISSUE THREAD

**Issue by menagerie198** [tgrosinger/slated-obsidian#21]
**Describe the bug**
Trying to update plugin fails

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Third Party Plugins' v0.0.3
2. Click on 'update' to 0.0.4
3. See error - 'Installing Update' > 'Failed to install plugin 'Slated''

**Desktop (please complete the following information):**
 - Win10
 - Obsidian Version: v0.10.6

**Comment by julianstoerig** [comment]
Hehe yeah, funny thing, same issue for me.

**Comment by tgrosinger** [comment]
Oh yeah, this one is my bad. One sec.

**Comment by julianstoerig** [comment]
It's fixed!

**Comment by menagerie198** [comment]
I have now been able to update. Thanks!
I now have another issue. The icon that renders from - [>], is now the right size (before it was HUGE and the colours reversed.
However, now I have the entire line of text being turned into a link in preview, and the text is cut short, by a [[link]]. 
![image](https://user-images.githubusercontent.com/7330436/103801716-095db100-5046-11eb-858f-cb3c58dea69f.png)
Should I open another issue?

**Comment by julianstoerig** [comment]
Yes, closing this issue and making a new one for the new issue is standard.

**Comment by menagerie198** [comment]
cool.
