### ISSUE TITLE
Pushed task formatting issue

### ISSUE THREAD

**Issue by menagerie198** [tgrosinger/slated-obsidian#22]
**Describe the bug**
A pushed task is now rendering the whole line of text like a link (in Edit mode!). In preview mode the 'link' is gone, but some of the text is being cut off by the [[link]] preceding it.

**To Reproduce**
Steps to reproduce the behaviour:
1. create a task, with a [[link]] at its head
![image](https://user-images.githubusercontent.com/7330436/103803731-dff25480-5048-11eb-8f01-96a8fa5f11d8.png)
Push that task into the future
![image](https://user-images.githubusercontent.com/7330436/103803456-80944480-5048-11eb-9f03-14cc720dfabc.png)
In Edit mode the text appears to be rendered as a link. In Preview mode there is no link, but the text is truncated after the [[link]]
![image](https://user-images.githubusercontent.com/7330436/103803900-2a73d100-5049-11eb-83d5-cab6d92d0bca.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Obsidian Version: 0.10.6
 - Slated Version: 0.0.4

**Additional context**

**Comment by tgrosinger** [comment]
A lot to unpack here. Thank you @menagerie198 for the detailed report.

I am going to break this down into two parts.

## Edit Mode

The issue you demo above in edit mode occurs even when Slated is disabled, leading me to believe this might be a bug in Obsidian. It occurs whenever there is `- [*] [[a link]] some text` where `*` can be anything.

I'll see if the Obsidian developers have some input here.

## Preview Mode

This is definitely the fault of Slated. I had not considered a line which might start with a link. I'll look into that.

**Comment by tgrosinger** [comment]
Update on the edit mode issue:

This seems to be an interaction between the two sets of square braces, causing the parser to think there is a [reference style link](https://www.markdownguide.org/basic-syntax/#reference-style-links). I am guessing it's then getting exacerbated by the wiki-style link rather than a normal markdown link.

**Comment by tgrosinger** [comment]
@menagerie198, it looks like the issue in edit mode is known by the Obsidian team and is tracked  [here in the forum](https://forum.obsidian.md/t/editor-parser-problems-in-lists-number-bullet-check/5795). Having your task start with text instead of a link is a work around for now, but unfortunately I can not offer a better solution.

I will fix the issue in preview mode though 🙂

**Comment by menagerie198** [comment]
The workaround is not too troublesome. Thanks for your work and attention. Now, where is that patreon...

**Comment by tgrosinger** [comment]
Haha , I appreciate it :-) No patreon, but there are a few links on the right sidebar of this repo homepage.

**Comment by tgrosinger** [comment]
I'm going to reopen this and use it to track the preview mode issue.

**Comment by tgrosinger** [comment]
Hmm, well I am having trouble reproducing the preview mode issue.

![image](https://user-images.githubusercontent.com/597386/103842879-a707af00-504b-11eb-84f2-c5aece439f08.png)

![image](https://user-images.githubusercontent.com/597386/103842856-9bb48380-504b-11eb-8f73-34201432c171.png)

**Comment by menagerie198** [comment]
It is now working OK on my machine.
![image](https://user-images.githubusercontent.com/7330436/103894522-f5b65700-50e6-11eb-93f2-c818c48d52f9.png)
The ranging is off, but that is something to do with my snippets/theme - it is all in line in a out-of-the-box Obsidian, as per your image. Either 0.0.4 sorted it, or it is a rogue effect of my styling that I missed (PEBCAK?)
