### ISSUE TITLE
Repeating task not creating if day already has a section header for tasks

### ISSUE THREAD

**Issue by ontrou** [tgrosinger/slated-obsidian#24]
**Describe the bug**
If you already have a Tasks section header e.g. ## Tasks for a given day , then a repeating task is not created for that day. The repeating task is created for those days that do not have ## Tasks (as expected).

**To Reproduce**
Set up a repeating task for a day that already has ## Tasks heading

**Expected behavior**
The repeating task should be created.

**Comment by tgrosinger** [comment]
Hi @ontrou,
I'm not able to reproduce this issue. It seems to create repeating tasks on days which already have the tasks heading for me. Can you please provide me a little more details?

- What version of Slated are you running (check in the settings)
- What are the contents of the file where the repeating task is created? What date is the file for?
- What are the contents of the file you expect the task to be created in after completing? What is the date of that file?

Thank you.

**Comment by ontrou** [comment]
Answers:
- Slated v.0.0.4
- test task created Tuesday: `Water plants  📅 every week on Tuesday, Wednesday, Thursday ^task-cefg`
- Task did not display Wednesday. On Thursday:  `Water plants  📅 every week on Tuesday, Wednesday, Thursday [[2021-01-05#^task-cefg|<< Origin]]`

I did notice something else if this helps: I have `## Tasks` in the middle of my template (i.e. various headers before and after). If the future daily page has not been created (i.e Thursday in above example), the repeating task IS present when I do create the page under a new `## Task` at the bottom of the page. If the future daily has already been created (i.e Wednesday in above example), the repeating task is NOT created.

**Comment by tgrosinger** [comment]
@ontrou I'm still having trouble reproducing this.

I tried testing with a file that looks like this and it correctly appended to the tasks section.

```
# Heading

Some content here

## Tasks

- [ ] An existing task

## Another Section

More content here
```

One note that might be important here is that Slated will not create tasks in the past. If a repeating tasks is scheduled on Wednesday, to repeat every Tues/Wed/Thurs and today is Friday, then when I check off that task on Wed today the next instance created will be on Tuesday, not on Thursday because Thursday has already passed.

Let me know if that makes sense, and if that happens to be the issue here.

**Comment by ontrou** [comment]
Thanks for your suggestions @tgrosinger. I've had a few other strange things happen in Obsidian, so I decided to delete the appimage and download again. And.. .  I am not having these problems with Slated anymore. Again, thank you for being so responsive.

**Comment by tgrosinger** [comment]
Oh awesome, well please don't hesitate to reopen this if you experience the issue again.
Thanks!
