### ISSUE TITLE
Commands not found in palette

### ISSUE THREAD

**Issue by ShreyasKallingal** [tgrosinger/slated-obsidian#31]
**Describe the bug**
When searching the command palette, there are no slater commands found. Installation, however, does succeed, and I am able to view the plugin options:
![Screen Shot 2021-01-18 at 10 55 54 PM](https://user-images.githubusercontent.com/23715862/104998577-534c7c80-59e0-11eb-9d34-6145da4403ec.png)

**To Reproduce**
1. Browse community plugins for Slated.
2. Install Slated and enable in settings.
3. Create task in a note.
3. Open command palette.
4. No Slated commands are found in palette.

**Expected behavior**
Opening command palette should show 2 commands related to Slated.

**Screenshots**
![Screen Shot 2021-01-18 at 10 58 27 PM](https://user-images.githubusercontent.com/23715862/104998813-af170580-59e0-11eb-8dd6-b88fdaa90875.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.6
 - Obsidian Version: v0.10.7
 - Slated Version: 0.0.6

**Additional context**
As an aside, I really appreciate the idea behind this plugin—just wish I could use it though! Thank you for your help :)

**Comment by tgrosinger** [comment]
Hello,
Can you please restart Obsidian to make sure the plugin is fully loaded? It should only need to be done once. For some reason enabling plugins does not always fully setup all the components.

Additionally, the commands will only show up in the palette when your cursor is on a task in edit mode before opening the palette. They do not work in preview mode yet (but there are plans in the future, see #10)

**Comment by ShreyasKallingal** [comment]
I tried restarting, reinstalling, and turning off all other plugins. Unfortunately, that didn't seem to work.

I also kept my cursor on a task, tried highlighting it, and clicked on various parts—none of which popped up the commands. Please let me know if I'm doing something wrong. Does the task have to be a link? 

Is there anywhere specifically that I should click on this image:
<img width="107" alt="Screen Shot 2021-01-19 at 11 57 24 AM" src="https://user-images.githubusercontent.com/23715862/105086041-80834400-5a4d-11eb-8f84-a3c5172cf92f.png">

**Comment by ShreyasKallingal** [comment]
Update: I have no idea what I did, but the plugin turned off automatically for a bit. Once I turned it back on, the commands are working. I will reopen this if I have any further problems. Sorry for the issue!
