### ISSUE TITLE
Send tasks among weekly and daily notes

### ISSUE THREAD

**Issue by wenlzhang** [tgrosinger/slated-obsidian#33]
**Is your feature request related to a problem? Please describe.**
In the current implementation, a link would be created automatically when moving a task from one daily note to another. This link can be especially useful when the task is created not within a daily note. This way, one can conveniently navigate back from the daily note to the note where the task is created.

Sometimes it would also be useful to just send tasks without creating any link. For instance, one may plan tasks in a weekly note, e.g. Week 20. After completing a task, Task A, within the weekly note Week 4 on a specific date, e.g. 2021-01-25, one may want to move Task A to the daily note 2021-01-25, to show what has been done on that day. Since Task A has already been completed before moving/sending it, it may not be necessary to create a link for it.

**Describe the solution you'd like**
Being able to send (without creating links) tasks among daily notes, weekly notes and among daily and weekly notes, e.g. send Task A from 2021-01-25 to 2021-01-26, from Week 4 to Week 5 and from Week 4 to 2021-01-25.

**Comment by tgrosinger** [comment]
Great idea, it's in the new release.
