### ISSUE TITLE
Slated causes a rendering error

### ISSUE THREAD

**Issue by ryanjamurphy** [tgrosinger/slated-obsidian#43]
**Describe the bug**
With a certain layout of task lists (described below), Slated causes Obsidian to render the following error message in-page.
![Screen Shot 2021-02-04 at 4 30 54 PM](https://user-images.githubusercontent.com/3618647/106968570-5c3e8d00-6706-11eb-9c15-5fb574bc49fa.png)

**To Reproduce**
Try the following text:
```
- [  ] Some task

- [>] Some rescheduled task ^task-blockid
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Obsidian Version: 0.10.12
 - Slated Version: 0.1.1

**Comment by ryanjamurphy** [comment]
The issue persists even when Slated's been disabled, which is funny. You must disable Slated and then reload the app to unload whatever Slated's doing to render the `[>]` icons.

**Comment by tgrosinger** [comment]
Oh nice, thanks for narrowing down how to repro this. Someone mentioned it in the forum earlier, but we couldn't get enough info for me to repro.

I'll look into this tomorrow.

**Comment by tgrosinger** [comment]
Interesting. When there is an empty line between two tasks, the rendering engine will keep those tasks in the same `ul` but put each list item in a `p` tag.

I look forward to when I can hook custom rendering code in before it has been rendered to html. It will be much more reliable!
