### ISSUE TITLE
Moving incomplete to Daily note doesn't work for embedded Daily folder

### ISSUE THREAD

**Issue by redfoxseattle** [tgrosinger/slated-obsidian#44]
**Describe the bug**
When I click "Move incompleted tasks to today" I get the error "Unable to Create a new file" because of embedded daily folder.

**To Reproduce**
1. Configure Daily Note to add child folders by changing format to: YYYY/MMM/YYYY-MM-DD-ddd (Adds file to folder: Daily Note > 2021 > Feb, with daily note named '2021-02-05-Friday')
2. Go to daily tasks to move
3. Open Command Palette and click "Move incomplete tasks to today"
4. See error - "Unable to Create a new file"

**Expected behavior**
I noticed that when I changed my Daily Note to be just the date format without the folders for YYYY/MMM, the plugin worked as expected and copied my incomplete tasks from one day to the next. I'm aware that adding the folders into the Daily Note file name is *kind of* a hack to enable Daily Note creation in subfolders, but it would be nice if the plugin recognized the subfolders.

**Screenshots**

![slated](https://user-images.githubusercontent.com/21209421/107102010-eef62f00-67cd-11eb-854a-6f75aa86fb86.jpg)

![2021-02-05_16-19-51](https://user-images.githubusercontent.com/21209421/107102024-00d7d200-67ce-11eb-8b91-00883bb5c8ba.jpeg)

**Desktop (please complete the following information):**
 - OS: OSX Catalina
 - Obsidian Version: v0.10.12
 - Slated Version: [e.g. 0.1.0] (Settings → Third-party plugin → Scroll to Slated)

**Additional context**

**Comment by tgrosinger** [comment]
@liamcain I think this might be an issue with the daily notes interface? Slated doesn't create that Notice at least.

**Comment by liamcain** [comment]
I added support for nested directories in v0.7.0 of the daily note interface, so this will actually work if you upgrade @tgrosinger.

**Comment by redfoxseattle** [comment]
Thanks! I will try Periodic Notes out.
