### ISSUE TITLE
Slated commands missing

### ISSUE THREAD

**Issue by adxsoft** [tgrosinger/slated-obsidian#45]
**Describe the bug**
Installed Slated plugin on Obsidian 10.12. The command palette is only showing one command (Move all incompleted tasks to today) when I enter *slated* into the command palette (Cmd P). Does not show the other commands Move task, skip task occurrence and configure repetition

**To Reproduce**
- install slated plugin
- Enable Slated plugin
- Cmd P
- enter 'slated'

**Expected behavior**
Should see all 4 commands for slated

**Screenshots**
![Screen Shot 2021-02-06 at 4 55 30 pm](https://user-images.githubusercontent.com/24862237/107110464-2af7c580-689c-11eb-9791-fc73b4e19b59.png)

**Desktop (please complete the following information):**
 - OS: OSX Sierra
 - Obsidian Version: 10.12
 - Slated Version: 0.1.1

**Additional context**

**Comment by adxsoft** [comment]
This issue only occurs if you are in todays note. If you go to an earlier note with open tasks you will see all 4 commands.
The documentation needs to make clearer that you need to go to the note with the open tasks in order to move the tasks into todays note.

**Comment by tgrosinger** [comment]
The other commands are only shown if your cursor is on a line with a task. In other words, the commands are not available when they could not be applied properly.

**Comment by firinael** [comment]
Can you please make it so the commands appear even when they're not properly applicable? I'd much rather get an error message than simply not find the commands at all and think I've encountered a bug.
