### ISSUE TITLE
Move all incompleted tasks to today does nothing

### ISSUE THREAD

**Issue by adxsoft** [tgrosinger/slated-obsidian#46]
**Describe the bug**
Created a new daily note via Calendar plugin. Has two previous daily notes as follows

Note Filename **2020-11-29.md**
Contents
## Tasks
- [ ] task 1
- [ ] task 2
- [ ] task 3

Note Filename **2021-02-21.md**
Note Contents
## Tasks
- [ ] Task A
- [ ] Task B

**To Reproduce**
1. Calndar plugin should have folder set to 'Daily Notes'
2. Create the 2 daily notes above in folder called Daily Notes
3. Click todays date on Calendar and choose create daily note
4. Cmd P
5. Enter command 'slated'
6. Chose move all incompleted tasks to today
7. Nothing happens

**Expected behavior**
Expected the *Move all incompleted tasks to today * command to create 5 tasks
-[ ] task 1
-[ ] task 2
-[ ] task 3
-[ ] Task A
-[ ] Task B
in todays Daily Note
**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX Sierra
 - Obsidian Version: 10.12
 - Slated Version: 0.1.1

**Additional context**
Note earlier issue with missing commands also reported which may be related

**Comment by adxsoft** [comment]
![Screen Shot 2021-02-06 at 5 26 02 pm](https://user-images.githubusercontent.com/24862237/107111025-aa879380-68a0-11eb-864e-628874bce16e.png)

![Screen Shot 2021-02-06 at 5 26 22 pm](https://user-images.githubusercontent.com/24862237/107111028-afe4de00-68a0-11eb-9338-005e78a8c421.png)

![Screen Shot 2021-02-06 at 5 26 39 pm](https://user-images.githubusercontent.com/24862237/107111032-b96e4600-68a0-11eb-8a84-040b603acfb7.png)

![Screen Shot 2021-02-06 at 5 27 01 pm](https://user-images.githubusercontent.com/24862237/107111034-bd01cd00-68a0-11eb-8ba0-15fddf3f05e0.png)

![Screen Shot 2021-02-06 at 5 27 10 pm](https://user-images.githubusercontent.com/24862237/107111059-f2a6b600-68a0-11eb-9bab-8d9e9b353bd1.png)

**Comment by franciscoj** [comment]
Hi!

I had this same issue when I started using slated. Then I realized that I needed to run the command from the past days, not from the current daily note.

In your example you'd have to go do `2020-01-21` and run the command, that will move all the tasks **in that note** to the current daily note.

**Comment by adxsoft** [comment]
Thanks for the quick response Fran. 

Looks like the description of the plug in needs to be clearer.

So you ‘push’ the open tasks to todays note rather than being in todays note and ‘pulling’ the open tasks from earlier notes.
You’re right it works perfectly now.

Very useful capability I will be using it from now on.

I also noticed before that I had missing slated commands when I was in todays note but when I am in the earlier note all 4 commands appeared.



Thank you very much for your help

Cheers
Allan @ adxsoft

**Comment by adxsoft** [comment]
Plugin does work provided you go to the note with the tasks to be moved to today

**Comment by tgrosinger** [comment]
Ah, I will rename that command to make it more clear. Thanks for the heads up.
