### ISSUE TITLE
Moving a task to new daily file doesn't correctly use template

### ISSUE THREAD

**Issue by tim-hilde** [tgrosinger/slated-obsidian#47]
I am using both the slated and templates plugin. When I'm moving a task to a day of which there is no file yet, the template placeholders are not replaced correctly. Instead of referring to the new date's title it is using the current one. Obviously this could also be a bug in the templater plugin, so I am posting this here and over at [https://github.com/SilentVoid13/Templater](https://github.com/SilentVoid13/Templater)

**Comment by tgrosinger** [comment]
I'm using `vault.read` and if the file does not exist, I just use an empty string for the file contents. I'll probably need input from @SilentVoid13 if there's something I should be doing different.

**Comment by tgrosinger** [comment]
FWIW it does work with the configured Daily Notes template.

**Comment by tim-hilde** [comment]
Hm...
To make it a bit more clearly maybe: the daily note template is actually used, but somehow does not work as expected. In my daily template I have this: 

# {{tp_title_date:f="dd, DD.MM.YYYY"}}

When creating say the file for February 19th it gets replaced by 

# Fr, 19.02.2021

But when I'm using the slated plugin to move a task from Feb 12th to a the 19th (which is not existing at this point), it is replaced by 
# Fr, 12.02.2021
the date of the origin.

**Comment by tgrosinger** [comment]
Oh wow. I have no idea what could be causing that. I just ask for the file contents 😮
Hopefully we can get some insight from SilentVoid13.

**Comment by tgrosinger** [comment]
I'm going to close this due to inactivity. If we hear from SilentVoid13 we can reopen this issue.

**Comment by liamcain** [comment]
I think the problem is that `tp_title` looks at the active pane's title rather than the title of the file that was just created. @tim-hilde, it should work with the built-in templates. So you should be able to use `{{date:dd, DD.MM.YYYY}}` to get what you're after.
