### ISSUE TITLE
Last subtask available only

### ISSUE THREAD

**Issue by Gadwood** [tgrosinger/slated-obsidian#48]
**Describe the solution you'd like**
I would like a way to filter all my task and see only the available to take action like omnifocus sequential project (ex: i dont need to see that i need to take the car out of the garage and  open the door before i have my cars key.) 

_- [ ] Taking the car out of the garage_ **(Not available in the task list)**
.....     - [ ] Taking my cars key **(Avalable in the task list)**
.....      _- [ ] Opening the garage door_ **(Not available in the task list)**

**Comment by tgrosinger** [comment]
I don't think we should do this when looking at a file directly, because I don't want to hide file contents. However this is something that I could probably work into the Task View that I am working on in #25.

I'm going to mark this on-hold until that project is further along.

**Comment by Gadwood** [comment]
Exactly my idea. I don't want to hide it in the file, only in the "review task" view. Sorry for my english, french is my first language. I know some time i'm not easy to understand, i'm missing world to explain my idea.


​_____________________

Guillaume Gadbois Gervais

514.419.3382 | 514.863.6659 (cell)

Rosemont, Montréal Qc
guillaume@gadbois.cc

________________________________
De : Tony Grosinger <notifications@github.com>
Envoyé : 11 février 2021 12:11
À : tgrosinger/slated-obsidian <slated-obsidian@noreply.github.com>
Cc : Gadwood <guillaume@gadbois.cc>; Author <author@noreply.github.com>
Objet : Re: [tgrosinger/slated-obsidian] Last subtask available only (#48)


I don't think we should do this when looking at a file directly, because I don't want to hide file contents. However this is something that I could probably work into the Task View that I am working on in #25<https://github.com/tgrosinger/slated-obsidian/issues/25>.

I'm going to mark this on-hold until that project is further along.

**Comment by tgrosinger** [comment]
No worries. Thanks for the suggestion 🙂

**Comment by tgrosinger** [comment]
After much thought, I am reducing the scope of Slated and am no longer planning on adding the Task View. Because of that, I do not think this feature fits into Slated.
