### ISSUE TITLE
Error line when inserting commment

### ISSUE THREAD

**Issue by Gadwood** [tgrosinger/slated-obsidian#49]
Hello, i've try to add a comment under a task ands getting this error.
I whanted to see some comment under the task to explain it without going to the origin

![ERROR1](https://user-images.githubusercontent.com/69422318/107637371-099c2e00-6c3c-11eb-9d43-65ecc8edd297.PNG)
![ERROR2](https://user-images.githubusercontent.com/69422318/107637373-099c2e00-6c3c-11eb-9955-53df60ed0f59.PNG)

**Comment by tgrosinger** [comment]
I'll investigate. Thanks for the report.

**Comment by tgrosinger** [comment]
Hmm, I am having trouble reproducing this. There was an issue like this a bit ago though. Can you please make sure you're on the latest version? Should be 0.1.2 or greater.

<img width="700" alt="Screen Shot 2021-02-13 at 8 59 12 AM" src="https://user-images.githubusercontent.com/597386/107855894-0b035d00-6dda-11eb-95b6-b66c063fc0bb.png">
<img width="665" alt="Screen Shot 2021-02-13 at 9 00 05 AM" src="https://user-images.githubusercontent.com/597386/107855895-0b9bf380-6dda-11eb-9064-8a54528b7a4b.png">

**Comment by tgrosinger** [comment]
Closing this based on inactivity. If you are able to produce this error again and provide more details please feel free to reopen.
