### ISSUE TITLE
Change Origin link for task

### ISSUE THREAD

**Issue by Gadwood** [tgrosinger/slated-obsidian#50]
Hello, the origin link on a moved task should link to the page it come from. Right now if I over the link I get a preview of the same task and inside it a link to the today’s note. I would prefer to know it come from which note/daily note. Maybe keep the link to block but write the note name which it came from instead of « origin »

**Comment by tgrosinger** [comment]
Can you show me an example of what that link looks like in edit mode?

You can also change the behavior of the origin link if you don't like that mode in the settings.

![image](https://user-images.githubusercontent.com/597386/107726821-c921cc00-6c9e-11eb-930c-6452929e1fca.png)

**Comment by Gadwood** [comment]
Would like something like this
![Capture d’écran, le 2021-02-12 à 20 17 14](https://user-images.githubusercontent.com/69422318/107837596-a90e0d80-6d6f-11eb-9205-c699bb157b4c.png)
i dont get any context with that preview. i dont know if there is a work around to see line before and after
![Capture d’écran, le 2021-02-12 à 20 20 31](https://user-images.githubusercontent.com/69422318/107837619-c8a53600-6d6f-11eb-9cf9-848abf6c56a4.png)

**Comment by tgrosinger** [comment]
Interesting. I don't do anything with the link previews (I don't use them) so I am not sure what could be breaking them.

Does the link work if you click on it?

**Comment by tgrosinger** [comment]
Closing due to inactivitiy.
