### ISSUE TITLE
Disalllow "move all incomplete" when looking at current days note

### ISSUE THREAD

**Issue by Gadwood** [tgrosinger/slated-obsidian#51]
**Describe the bug**
I’ve used the command to move note to today’s note by error (on the daily note of the same day that we are) everything have moved in the 5th dimension 

**To Reproduce**
Move all incomplete task to today’s not the same day of the current daily note

**Expected behavior**
Telling my I’m doing weird things or create it into the tomorrow daily note.

**Desktop (please complete the following information):**
 - OS: Macis
 - Obsidian Version: [v0.11.0]
 - Slated Version: [0.1.2]

**Comment by tgrosinger** [comment]
Hi @Gadwood, I am not quite following what behavior you are seeing. I think you are using the "Move incompleted tasks from current file to today" command? That command is designed to only move tasks from the daily note that is currently focused into the daily note for the current day. Let me know if that makes sense, and if you can provide any more details about what you're seeing.

Thanks for the bug report 🙂

**Comment by Gadwood** [comment]
Yes but i accidentally used it on my note from the 12 february, on that day (sameday) and instead of getting an error everything has desapear I've lost all my task.
