### ISSUE TITLE
Repeating tasks often created on day before they should be

### ISSUE THREAD

**Issue by tgrosinger** [tgrosinger/slated-obsidian#53]
For example, if the task is "Feed the dog ; Every Sunday" and I check it off, it will be recreated on the following Saturday. I don't have a perfect reproduction steps yet, but it definitely is happening a lot.

**Comment by tgrosinger** [comment]
Of course I can not get this to repro when I try

**Comment by tgrosinger** [comment]
I'm adding a much better debug message so I can hopefully track this down.

**Comment by tgrosinger** [comment]
I actually haven't run into this in a while now. Not sure why. Maybe I accidentally fixed it?

**Comment by sebastianromano** [comment]
Hi Tony
Thank you so much for this wonderful plugin!
Unfortunately, I still have this issue (as of yesterday) and resort to manually deleting the additional tasks (on the wrong day). 
Did you do anything to change the behavior of the repeating tasks - deleting and creating again e.g.? 
Best 
Sebastian

**Comment by sebastianromano** [comment]
Hi Tony - after a clean install of Slated, I no longer have this issue

**Comment by tgrosinger** [comment]
Glad to hear it. I'm going to close this issue now.
