### ISSUE TITLE
Add an option for not moving sub-items

### ISSUE THREAD

**Issue by wenlzhang** [tgrosinger/slated-obsidian#54]
**Is your feature request related to a problem? Please describe.**
Sometimes one may want to keep sub-tasks and/or sub-items in their original locations, as it may be more convenient to check the related sub-tasks and/or sub-items if they are placed in their original location/context.

**Describe the solution you'd like**
It would be great if there would be an option for choosing if one wants to move sub-items together with the main task or not.

**Comment by tgrosinger** [comment]
Would you imagine this as a global option? Or in the move dialog each time you want to move a task?

**Comment by wenlzhang** [comment]
For my use case, I prefer not to move the sub-items. So, it would be better for it to be a global option.

**Comment by wenlzhang** [comment]
After further testing, it would also work if this option can be set like the one for the bi-directional links, i.e. one choose to move the sub-items or not in the calendar interface. The reason for this is that, if one wants to move tasks from certain types of notes, e.g. daily/weekly or meeting notes, it might be more convenient to have the sub-items, especially sub-tasks, moved into the new note together with the main task, as the meeting notes may be archived after summarizing them and it would be easier to check the sub-items in the new note.

Sorry for the late supplement... Hope it is not too late to add this.

**Comment by rosewills** [comment]
I would really appreciate this feature. My daily todo lists have many subtasks, and when I roll them over, they become separated from the parent task.
