### ISSUE TITLE
Add an option for not moving task headers

### ISSUE THREAD

**Issue by wenlzhang** [tgrosinger/slated-obsidian#55]
**Is your feature request related to a problem? Please describe.**
In the latest version of the plugin, a task would be moved together with its headings. However, sometimes one may want to just move the tasks, without the headings being moved/copied. For instance, the heading level of the original task might be:
```
#### Header 4
##### Header 5

- [ ] Task A
```
The task may be moved to a daily note with the `## Tasks` as the heading level, which is different from the original heading level. Or, sometimes, one may not want to move/copy the heading text to the corresponding daily note.

**Describe the solution you'd like**
Add an option for selecting whether to move/copy task heading to a daily note. The option can be like the one for the bidirectional link, or it can be placed in the plugin setting interface.

**Comment by tgrosinger** [comment]
In the interest of keeping this plugin simple, I think this is going to fall outside the scope of this plugin. You can of course use Slated to move a task to another file, and then move it with copy/paste within that file.
