### ISSUE TITLE
"move all tasks" duplicates nested tasks

### ISSUE THREAD

**Issue by fakeharxy** [tgrosinger/slated-obsidian#57]
**Describe the bug**
When you use the "Move incomplete tasks from the current file to today" hotkey, it will duplicate all tasks that are nested. I think it's because it moves the tasks from the bottom and moves up - which means it does all sub-tasks _then_ moves the parent task - which contains all the subtasks

**To Reproduce**
make a task list in a file:
- [ ] Task parent
  - [ ] task one
  - [ ] task two
  - [ ] task three

And then run "move incomplete tasks to today" and watch as it duplicates all the nested tasks

**Expected behavior**
the parent task is moved over, with the sub-tasks, but each subtask only appearing in the new file once.

**Screenshots**
Will add if necessary, but I think you probably get it from the description :)

**Desktop (please complete the following information):**
 - OS: macOS
 - Obsidian Version: most recent
 - Slated Version: most recent

Thanks! The Slated plugin is amazing :) :)

**Comment by tgrosinger** [comment]
Thanks for the bug report. I was able to reproduce this and will get it fixed!
