### ISSUE TITLE
Respect link format (wikilinks or markdown links) of the user

### ISSUE THREAD

**Issue by finn-matti** [tgrosinger/slated-obsidian#61]
**Is your feature request related to a problem? Please describe.**
Right now slated just assumes users would want to use wikilinks, e. g. when moving incomplete tasks.

**Describe the solution you'd like**
Either make it a configurable option what kind of links to use, or respect the default obsidian option "Use [[wikilinks]]" setting.

**Describe alternatives you've considered**
[Use wikilinks to mdlinks plugin to fix the link style manually.](https://github.com/agathauy/wikilinks-to-mdlinks-obsidian)

**Additional context**
Obsidian 0.11.0
Slated 0.2.1

**Comment by tgrosinger** [comment]
Hello,
Are you referring to the links between files that Slated creates when you move tasks?

**Comment by finn-matti** [comment]
Yes. 

<img width="591" alt="Screen Shot 2021-02-28 at 10 12 03" src="https://user-images.githubusercontent.com/56148301/109411837-6a05cc00-79ad-11eb-865d-7d5590a6c2dd.png">

**Comment by tgrosinger** [comment]
Bidirectional links have been removed in the latest version of Slated.
