### ISSUE TITLE
Global option to default “Create bi-directional links” to “off”

### ISSUE THREAD

**Issue by harmtemolder** [tgrosinger/slated-obsidian#64]
I rarely want to create bi-directional links when moving a task. How do you feel about creating a global option that defaults this to “off”? this consists of:

1. Moving a single task manually, where I can currently uncheck this option
2. Moving all incomplete tasks to today, where I don’t have this option

**Comment by tgrosinger** [comment]
Bidirectional links have been removed in the latest release.
