### ISSUE TITLE
Placeholders from the calendar plugin are not recognized

### ISSUE THREAD

**Issue by argenos** [tgrosinger/slated-obsidian#65]
**Describe the bug**
The new placeholders from the calendar plugin are not recognized

**To Reproduce**
1. Add {{yesterday}} and {{tomorrow}} to the daily note template
2. Move a task from e.g. today to some other day
3. Check new note and placeholders are not replaced

**Expected behavior**
Placeholders would be replaced

**Screenshots**
![image](https://user-images.githubusercontent.com/5426039/114172592-22704980-9936-11eb-87f7-9ebef50b4741.png)

**Desktop (please complete the following information):**
 - OS: Linux 18.04
 - Obsidian Version: v0.11.13
 - Slated Version: 0.2.2
 - Calendar version: 0.1.5
 - Periodic notes version: 0.0.15

**Additional context**
It might be fixed just by updating the `obsidian-daily-notes-interface`, but I'm not entirely sure. @liamcain might know best.

**Comment by tgrosinger** [comment]
As you suspected, this is solved in the latest release of Slated (0.3.0) which has updated to the latest obsidian-daily-notes-interface.
