### ISSUE TITLE
Support bi-directional links when moving tasks

### ISSUE THREAD

**Issue by wenlzhang** [tgrosinger/slated-obsidian#66]
I noticed that bi-directional links is removed when moving and repeating tasks.

I truly understand that adding bi-directionals links when repeating tasks among daily notes may not be necessary, as such tasks may be simple/isolated tasks that do not belong to a project.

However, is it possible to add back bi-directional links when moving tasks? This feature can be very useful when moving a task from a project page, as one can easily navigate from a daily note to the original location of the task.

**Comment by tgrosinger** [comment]
@wenlzhang, I appreciate the desire for the bidirectional links, however at this time I will not be adding them. You may use an older version of Slated (0.2.2).

It's possible I will add some form of linking in the future, but there are no plans to at the moment.
Thank you.
