### ISSUE TITLE
Move all open tasks in daily notes earlier than today to today's daily note

### ISSUE THREAD

**Issue by dcoales** [tgrosinger/slated-obsidian#75]
At the end of each day I try to remember to move all incomplete tasks to a future date OR to move them to a general task list.  Sometimes however I forget and then these tasks can get lost in previous daily notes.

It would be great if there were a command that would scan all daily notes for days earlier than today (for performance this could be limited to just the last N days which could be configured in settings) and move any incomplete notes to today's daily note.

I have seen in the documentation for slated images showing such an option in the command list but it doesn't appear for me. Is this functionality actually available and I just don't know how to turn it on :-).

Fabulous plugin BTW.  It's one of the reasons I came back to Obsidian after trying it and finding it unsuitable for task management.

**Comment by tgrosinger** [comment]
@dcoales I'm trying very hard to keep the number of commands in Slated as slim as possible. One alternative I may suggest though is using the calendar plugin. It will display an open circle on days which have uncompleted tasks.

![incomplete-tasks](https://raw.githubusercontent.com/liamcain/obsidian-calendar-plugin/master/images/how-to-pin.png)

You might also look at the Vantage plugin, which can help build an embedded search query that can show you uncompleted tasks from previous days.

Let me know if either of those suggestions are helpful.

**Comment by dcoales** [comment]
Thanks, both of those suggestions are really helpful.  I had no idea the open circles meant incomplete tasks on the calendar view !
